### PR TITLE
DL-4595 - Remove feedback page in Ated

### PR DESCRIPTION
**Pull request by MarjanMubarok**
# JIRA Story or Github Number - descriptive title

**Bug fix / New feature** (delete as appropriate)

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## Checklist

*Reviewee* (Replace with your name)
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

*Reviewer* (Replace with your name)
 - [ ]  I've confirmed that every effort has been made to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've confirmed appropriate tests has been included with any code added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've confirmed code was added using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

### CODE REVIEW

**Comment by Sir-Iyke** [comment]
Why is this marked as "Do Not Merge"?

**Comment by Sir-Iyke** [comment]
Unit test coverage is down 0.42% I think this is because the feedback view is no longer being tested. Can this be double checked please.

**Comment by nadinJ** [comment]
> Why is this marked as "Do Not Merge"?

I think because when originally Marjan pushed his changes, his ATED ATs were not passing

**Comment by nadinJ** [comment]
> Unit test coverage is down 0.42% I think this is because the feedback view is no longer being tested. Can this be double checked please.

I'm getting coverage of 81.53%

**Pull request merged**
