### PR TITLE
DL-4860 GTM Implementation

### PR DESCRIPTION
**Pull request by Sir-Iyke**
DL-4860 GTM Implementation

**New feature** 

Added tracking consent snippet

To test locally make sure you use your browser in private/incognito mode. Also make sure you are running ‘TRACKING_CONSENT_FRONTEND’ via service-manager

Acceptance tests : https://github.com/hmrc/ated-acceptance-tests/pull/85

## Checklist

*Reviewee* (Iyke)
 - [x]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [x]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [x]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [x]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [x]  I've run a dependency check to ensure all dependencies are up to date

*Reviewer* (Replace with your name)
 - [ ]  I've confirmed that every effort has been made to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've confirmed appropriate tests has been included with any code added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've confirmed code was added using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

### CODE REVIEW

**Comment by Sir-Iyke** [comment]
I tested the banner locally and it appears and works fine. However I wasn't sure if we had to create any unit or acceptance tests at this stage.
I also wasn't sure if I had to leave localhost:12345 in there

**Comment by paulanderson1234** [comment]
I’m not sure the changes you have applied match what we discussed in refinement 

I thought we were removing the google analytics entry in application.conf and replacing it with the snippet mentioned as you have done

The bit about adding it to the main I’m not sure we should be doing at this stage.

The testing to get it to pop up was to manually append the following to the url : ?enableTrackingConsent=true

There was discussion about writing an AT in its own feature that went to one of the pages with this url and checking the banner is displayed

I could be wrong though ?

**Comment by Sir-Iyke** [comment]
The banner won't show without the changes to main that I added
I could definitely create ATs for this if that's what we should be doing at this stage?

**Comment by Sir-Iyke** [comment]
To test locally make sure you use your browser in private/incognito mode. Also make sure you are running ‘TRACKING_CONSENT_FRONTEND’ via service-manager

Acceptance tests : https://github.com/hmrc/ated-acceptance-tests/pull/85

**Comment by Sir-Iyke** [comment]
Service Manager Config changes : https://github.com/hmrc/service-manager-config/pull/3241

**Review by MarjanMubarok — APPROVED** [review]

**Pull request merged**
